export default {
  SET_TRACK_PLAYING: 'SET_TRACK_PLAYING',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_PW_TRACK: 'SET_PW_TRACK',
  SET_PW_WHY: 'SET_PW_WHY',
  FETCH_TRACKS_REQUEST: 'FETCH_TRACKS_REQUEST',
  FETCH_TRACKS_SUCCESS: 'FETCH_TRACKS_SUCCESS',
  FETCH_TRACKS_FAILURE: 'FETCH_TRACKS_FAILURE',
  FETCH_PW_REQUEST: 'FETCH_PW_REQUEST',
  FETCH_PW_SUCCESS: 'FETCH_PW_SUCCESS',
  FETCH_PW_FAILURE: 'FETCH_PW_FAILURE'
}
