export default {
  SET_TOP_TYPE: 'SET_TOP_TYPE',
  SET_SEARCH_TYPE: 'SET_SEARCH_TYPE',
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_PW_TRACK: 'SET_PW_TRACK',
  FETCH_TOP_REQUEST: 'FETCH_TOP_REQUEST',
  FETCH_TOP_SUCCESS: 'FETCH_TOP_SUCCESS',
  FETCH_TOP_FAILURE: 'FETCH_TOP_FAILURE',
  FETCH_SEARCH_REQUEST: 'FETCH_SEARCH_REQUEST',
  FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
  FETCH_SEARCH_FAILURE: 'FETCH_SEARCH_FAILURE',
  FETCH_PW_REQUEST: 'FETCH_PW_REQUEST',
  FETCH_PW_SUCCESS: 'FETCH_PW_SUCCESS',
  FETCH_PW_FAILURE: 'FETCH_PW_FAILURE'
}
